# .github/copilot.yml

version: 1

# Global suggestion settings
suggestion:
  enable: true      # 是否啟用 Copilot 建議
  autoprompt: true  # 自動提示建議
  frequency: medium # 建議出現頻率: low, medium, high

# File-level overrides (ordered by priority)
files:
  - pattern: "src/app/domain/**/*.ts"
    suggestion:
      enable: true
      frequency: high

  - pattern: "src/app/application/**/*.ts"
    suggestion:
      enable: true
      frequency: high

  - pattern: "src/app/infrastructure/**/*.ts"
    suggestion:
      enable: true
      frequency: medium

  - pattern: "src/app/presentation/**/*.ts"
    suggestion:
      enable: true
      frequency: medium

  - pattern: "src/app/**/*.component.ts"
    suggestion:
      enable: true
      frequency: low

  - pattern: "**/*.spec.ts"
    suggestion:
      enable: false

# Included paths (primary areas we care about)
include:
  - "src/app/domain/**"
  - "src/app/application/**"

# Excluded paths
exclude:
  - "node_modules/**"
  - "dist/**"
  - "dataconnect-generated/**"
  - "src/dataconnect-generated/**"

