name: Angular CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  actionlint:
    name: Lint GitHub workflows
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run actionlint
        uses: rhysd/actionlint-action@v1

  ci:
    name: Install / Lint / Typecheck / Test / Build
    runs-on: ubuntu-latest
    needs: actionlint
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 24
          cache: 'pnpm'
          cache-dependency-path: pnpm-lock.yaml

      - name: Install dependencies (pnpm)
        run: pnpm install --frozen-lockfile

      - name: Run ESLint
        run: pnpm run lint --if-present

      - name: Type check (tsc)
        run: pnpm exec tsc --noEmit

      - name: Run tests
        run: pnpm run test -- --watch=false --browsers=ChromeHeadless

      - name: Dependency cruise (validate layer boundaries)
        run: pnpm run depcruise || true

      - name: Build (production)
        run: pnpm run build -- --configuration=production

  codeql:
    name: CodeQL Analysis
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write
    steps:
      - uses: actions/checkout@v3
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: javascript
      - name: Autobuild
        uses: github/codeql-action/autobuild@v2
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2
