/**
 * Models Index
 * Auto-generated by refactoring tool
 */

// export * from './workspace-create-result.model'; (Moved to @workspace)
// export * from './workspace-create-result.validator'; (Moved to @workspace)
export { WorkspaceCreateResult, isValidWorkspaceCreateResult } from '@workspace/application';



export * from './identity.view-model';
export * from './user-avatar.view-model';
